version: '3'

services:
  backend:
    build:
      context: ./backend/docker
      dockerfile: backend.docker
    volumes:
      - ./backend/build/libs/app.jar:/backend/app.jar
    ports:
      - "8081:80"

  frontend-nginx:
    build:
      context: ./frontend/docker
      dockerfile: frontend.docker
    volumes:
      - ./frontend:/frontend
      - ./frontend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    ports:
      - "8080:80"

  frontend-nodejs:
    image: node:17-alpine3.14
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    tty: true